FROM python:3.10-slim
WORKDIR /app
COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
COPY spark_preprocess.py /app/spark_preprocess.py
COPY train_autoencoder.py /app/train_autoencoder.py
CMD ["python","/app/train_autoencoder.py"]