apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: model-serving
  labels:
    app: model-serving
spec:
  replicas: 2
  selector:
    matchLabels:
      app: model-serving
  strategy:
    blueGreen:
      activeService: model-serving-active
      previewService: model-serving-preview
      autoPromotionEnabled: false
  template:
    metadata:
      labels:
        app: model-serving
    spec:
      serviceAccountName: vault-auth-sa
      containers:
        - name: model-serving-container
          image: registry.digitalocean.com/hadii/model-serving:latest
          env:
            - name: VAULT_ADDR
              value: "http://vault.vault.svc.cluster.local:8200"
            - name: VAULT_PATH_AUTH
              value: "auth/kubernetes/login"
            - name: VAULT_ROLE
              value: "mlops-serving"
            - name: VAULT_SECRET_PATH
              value: "secret/data/mlops/base/model-serving"
            - name: MODEL_URI
              value: "mlruns/0/some_run/artifacts/pr_autoencoder"
            # Code in serve_model.py references these to load from Vault or to load the model URI
---
apiVersion: v1
kind: Service
metadata:
  name: model-serving-active
  labels:
    app: model-serving-active
spec:
  selector:
    app: model-serving
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: model-serving-preview
  labels:
    app: model-serving-preview
spec:
  selector:
    app: model-serving
  ports:
    - port: 80
      targetPort: 80
